### PR TITLE
Devise int

### PR DESCRIPTION
**Pull request by MelanieJae**
Devise integration; player model created

### CODE REVIEW

**Comment by MelanieJae** [comment]
1. re-did devise integration
2. fixed player model issue
3. fixed static pages routes.rb typo
4. created static_pages controller with index action

**Comment by CynrickChiu** [comment]
Hi Melanie,

I think there are merge confict messages in the schema.rb file causing the Travis CI to fail the tests.

**Comment by MelanieJae** [comment]
Hi Cynrick: You're absolutely right, there was a whole bunch of merge conflicts but hopefully they're fixed now. Thanks!

Melanie

**Comment by CynrickChiu** [comment]
I think it looks good now! If everyone agrees, we can go ahead and merge it.

**Comment by MelanieJae** [comment]
Yes, finally I think it's all good. Thanks everyone for your help and especially your patience :)

Melanie

**Comment by AndyAbplanalp** [comment]
Looks good

**Pull request merged**
